export const FILTERS = {
  "genres":
    [
      "1950s",
      "1950s rock",
      "1960s",
      "1960s pop",
      "1960s rock",
      "1970s",
      "1970s pop",
      "1970s rock",
      "1980s",
      "1990s",
      "1990s pop",
      "1990s rock",
      "2-step",
      "2000s pop",
      "2000s rock",
      "2010s pop",
      "2010s rock",
      "2020s pop",
      "achievement",
      "acid",
      "acid house",
      "acid jazz",
      "acid lounge",
      "acoustic",
      "acoustic americana",
      "acoustic blues",
      "acoustic folk",
      "acoustic jazz",
      "acoustic pop",
      "acoustic rock",
      "action",
      "adult",
      "adult contemporary",
      "adventure",
      "adventure fantasy",
      "advertising",
      "africa western africa",
      "african",
      "african dances",
      "african influenced",
      "african jazz",
      "afro house",
      "afro-cuban jazz",
      "afrofunk",
      "aggressive",
      "alternative",
      "alternative country",
      "alternative hip hop",
      "alternative pop",
      "alternative R&B",
      "alternative rock",
      "ambient",
      "ambient atmosphere",
      "ambient chill out",
      "american folk dance",
      "american roots rock",
      "americana",
      "anthem",
      "anthem rock",
      "aor",
      "appalachian",
      "archive",
      "argentine tango",
      "asia east asia",
      "asia east asia china peoples republic of china",
      "asia east asia japan",
      "asia south asia india",
      "asian",
      "asian beats",
      "asian influenced",
      "atmospheric",
      "authentic indigenous",
      "avant-garde",
      "avant-garde classical",
      "back end",
      "background",
      "background elevator",
      "ballad",
      "ballet",
      "ballroom tango",
      "ballroom waltz",
      "banda",
      "barn dance hoe down",
      "baroque",
      "baroque jazz",
      "baseball",
      "basketball",
      "bass",
      "batucada",
      "beach house",
      "beat",
      "beautiful",
      "bebop",
      "bed",
      "beds",
      "belly dance",
      "bhangra",
      "bhangra desi beats",
      "big band",
      "big band jazz",
      "big beat",
      "black metal",
      "bloopers",
      "bluegrass",
      "blues",
      "blues folk",
      "blues jazz",
      "blues rhythm",
      "blues rock",
      "bollywood",
      "boogie woogie",
      "boom",
      "boom bap",
      "bossa nova",
      "boy band",
      "braam",
      "brass",
      "breakbeat",
      "breakdance",
      "breakdance electro",
      "bright",
      "bright optimistic",
      "brit",
      "brit pop",
      "buddhist",
      "bugle call",
      "build",
      "cajun",
      "cajun zydeco",
      "calypso",
      "canadian",
      "caribbean",
      "carol",
      "cartoon",
      "catholic",
      "celtic",
      "celtic influenced",
      "celtic rock",
      "cha cha",
      "chamber",
      "chanson",
      "chart pop",
      "chase",
      "cheese",
      "cheesy",
      "chemical beats",
      "chicago",
      "chicago blues",
      "children",
      "chill out",
      "chill out downtempo",
      "chill wave",
      "chinese",
      "chiptune",
      "choral",
      "choral oratorio",
      "christian",
      "christmas",
      "cinematic",
      "circus",
      "classic",
      "classic orchestral",
      "classic R&B",
      "classic rock",
      "classic soul",
      "classical",
      "classical 20th century",
      "classical baroque",
      "classical concerto",
      "classical contemporary",
      "classical contemporary modern",
      "classical fanfare",
      "classical fusion",
      "classical influence",
      "classical march",
      "classical medieval",
      "classical minimalism",
      "classical piano",
      "classical renaissance",
      "classical rock",
      "classical romantic",
      "classical waltz",
      "clock",
      "club",
      "club electronica",
      "club electronica house",
      "club house",
      "club pop",
      "cocktail",
      "cocktail piano",
      "cold drone",
      "college",
      "comedy",
      "comedy fanfare",
      "comedy kids",
      "commercial",
      "commercial chart house",
      "communication",
      "communication news",
      "conga",
      "contemporary",
      "contemporary christian",
      "contemporary folk",
      "contemporary jazz",
      "contemporary r&b",
      "contemporary soul",
      "contemporary world music",
      "cool",
      "cool downtempo",
      "corporate",
      "corporate fanfare",
      "corporate pop",
      "country",
      "country blues",
      "country folk",
      "country hip hop",
      "country pop",
      "country rock",
      "country western",
      "cowboy",
      "crime",
      "crime scene",
      "crooner",
      "cumbia",
      "czech",
      "dance",
      "dancehall",
      "dansband",
      "dark",
      "daytime tv",
      "death metal",
      "deep funk",
      "delta blues",
      "depe house",
      "detective",
      "detroit soul",
      "dirty south",
      "disco",
      "disco house",
      "diy",
      "documentary",
      "documentary news",
      "doo wop",
      "downtempo",
      "drama",
      "drama emotion",
      "drama mystery",
      "drama nostalgia",
      "drama tension drone",
      "dramatic",
      "dramatic classical",
      "dramedy",
      "dream house",
      "dream pop",
      "drone",
      "drum and bass",
      "drum and bass jungle",
      "drum corps",
      "drumkit",
      "drumline",
      "dub",
      "dub step",
      "east coast",
      "east coast hip hop",
      "eastern europe",
      "easy listening",
      "easy listening mor",
      "eccentric quirky",
      "eclectic",
      "edm",
      "effects",
      "electro",
      "electro clash",
      "electro funk",
      "electro house",
      "electro jazz",
      "electro pop",
      "electro swing",
      "electronic",
      "electronica",
      "electronica retro",
      "elevator",
      "emo",
      "emotional",
      "end fanfares",
      "english",
      "entertainment",
      "environment",
      "epic",
      "epic classical",
      "ethereal",
      "ethnic",
      "ethnic dance pop style",
      "ethnic fusion",
      "ethnic travel",
      "euphoric house",
      "euro beat",
      "euro dance",
      "euro pop",
      "europe eastern europe",
      "europe northern europe england",
      "europe northern europe ireland",
      "europe northern europe scandinavia",
      "europe northern europe scotland",
      "europe northern europe united kingdom",
      "europe southern europe greece",
      "europe southern europe italy",
      "europe southern europe spain",
      "europe western europe austria",
      "europe western europe france",
      "europe western europe germany",
      "europe western europe germany bavaria",
      "europe western europe switzerland",
      "exercise fitness recreational",
      "exotic",
      "expansive",
      "experimental",
      "experimental dance",
      "experimental jazz",
      "experimental rock",
      "extreme",
      "factual",
      "fairytale",
      "family",
      "family adventure",
      "fanfare",
      "fanfare charge",
      "fantasy",
      "fantasy dreamy",
      "fashion",
      "fashion glamour",
      "feel good",
      "film",
      "film human drama",
      "film science fiction",
      "film score",
      "film score cinematic",
      "film score orchestral",
      "film score trailer",
      "film tv",
      "flamenco",
      "flamenco dance",
      "folk",
      "folk contemporary",
      "folk gypsy",
      "folk native american",
      "folk pop",
      "folk rock",
      "folk traditional american ethnic",
      "folk traditional ethnic",
      "folksy",
      "food",
      "football american",
      "free jazz",
      "freeform avant garde",
      "freeform jazz",
      "french",
      "french house",
      "fun",
      "funk",
      "funk rock",
      "funk soul",
      "funk soul r&b",
      "funky",
      "funky house",
      "fusion",
      "fusion hybrid",
      "futuristic",
      "futuristic bass",
      "futuristic garage",
      "futuristic jazz",
      "futuristic r&b",
      "g funk",
      "game",
      "game show",
      "gangsta",
      "garage",
      "garage rock",
      "general",
      "generic",
      "german",
      "girl band",
      "glam",
      "glam rock",
      "glitch",
      "global",
      "goa trance",
      "gospel",
      "goth rock",
      "gothic",
      "gothic rock",
      "grime",
      "gritty",
      "groovy",
      "grunge",
      "grupero",
      "guitar",
      "guitar solo",
      "gypsy",
      "halloween",
      "handbag house",
      "happy",
      "hard",
      "hard hip hop",
      "hard house",
      "hard rock",
      "hardcore",
      "hardcore electronica",
      "hardcore rock",
      "heartfelt",
      "heartland",
      "heavy metal",
      "heroic",
      "hi tech",
      "high drones",
      "high non rhythmic drones",
      "high rhythmic drones",
      "hillbilly",
      "hindu",
      "hip hop",
      "hip hop r&b",
      "hip hop urban",
      "hip hop zombie",
      "historical",
      "hits",
      "hits stings",
      "holiday",
      "hong kong",
      "honky tonk",
      "hopeful",
      "horror",
      "hot club",
      "hot club of france",
      "house",
      "house club",
      "hybrid",
      "hybrid orchestral",
      "hybrid trailer",
      "ibiza trance",
      "imaging",
      "impressionist",
      "indian",
      "indie",
      "indie alternative rock",
      "indie dance",
      "indie folk",
      "indie pop",
      "indie pop rock",
      "indie rock",
      "industrial",
      "industrial rock",
      "industry",
      "inspirational",
      "inspiring",
      "investigation",
      "islamic",
      "island",
      "japan",
      "jazz",
      "jazz blues",
      "jazz dixieland",
      "jazz funk",
      "jazz fusion",
      "jazz house",
      "jazz rock",
      "jazz traditional",
      "jazz waltz",
      "jazz west coast",
      "jewish",
      "jig dance",
      "jingles",
      "jive rock roll",
      "jump jive",
      "jungle",
      "jungle dance music",
      "k-pop",
      "keys piano",
      "kid",
      "kid pop",
      "kitsch",
      "kitsch cheesy",
      "kitsch lounge",
      "kitsch retro",
      "klezmer",
      "lasers zaps",
      "late night",
      "latin",
      "latin america",
      "latin america caribbean west indies cuba",
      "latin america caribbean west indies jamaica",
      "latin america central america mexico",
      "latin america south america argentina",
      "latin america south america brazil",
      "latin america south america colombia",
      "latin dance",
      "latin folk",
      "latin house",
      "latin influenced",
      "latin jazz",
      "latin pop",
      "latin traditional dance",
      "leftfield",
      "leisure",
      "leisure lifestyle",
      "lifestyle",
      "light",
      "light drama",
      "liquid funk",
      "lo-fi",
      "lo-fi chill beats",
      "lo-fi hip hop",
      "logos",
      "loop",
      "lounge",
      "lounge chill out",
      "lounge core",
      "love",
      "love romance",
      "low drones",
      "low non rhythmic drones",
      "low rhythmic drones",
      "lullabies",
      "lullaby",
      "luxury",
      "main title",
      "mainstream hip hop",
      "mambo",
      "mariachi",
      "medieval",
      "meditation",
      "merengue",
      "mersey",
      "metal",
      "mexican banda",
      "miami",
      "middle east",
      "middle eastern",
      "middle of the road",
      "military",
      "military fanfare",
      "military march",
      "military war",
      "minimal",
      "minimal techno",
      "minimalism",
      "minimalist",
      "minimalist style",
      "minuet",
      "modern",
      "modern blues",
      "modern classical",
      "modern country",
      "modern folk",
      "modern jazz",
      "modern latin",
      "modern neo classical",
      "modern orchestral",
      "modern r&b",
      "motivational",
      "motor sports",
      "motown",
      "motown old school r&b",
      "movie",
      "music elements",
      "musique concrete",
      "muzak",
      "mysterious",
      "mystery",
      "mystery investigation",
      "national folk",
      "national folk dance",
      "native american",
      "nature",
      "nature atmospheric drone",
      "nature pastoral",
      "nature science",
      "neo classical",
      "neo soul",
      "neo swing",
      "neutral drone",
      "new acoustic",
      "new age",
      "new orleans jazz",
      "new releases",
      "new wave",
      "news",
      "newsreel",
      "noir",
      "noise",
      "norteno",
      "north america usa east coast",
      "north america usa hawaii",
      "northern soul",
      "nostalgia",
      "nu disco",
      "nu folk pop",
      "nu jazz",
      "nu metal",
      "nu school breaks",
      "nursery rhymes",
      "nursery rhymes well known themes",
      "oceania south pacific australia",
      "old school",
      "old school funk",
      "old school hip hop",
      "opening fanfares",
      "opera",
      "opera aria",
      "opera overture",
      "orchestral",
      "orchestral americana",
      "orchestral hybrid",
      "orchestral pop",
      "orchestral symphony",
      "other",
      "other forms ballad",
      "other forms march",
      "other forms march marches band",
      "other forms march military band",
      "pacific northwest",
      "panoramic",
      "pastoral",
      "percolating",
      "percussion",
      "piano",
      "piano solo",
      "polka",
      "pop",
      "pop punk",
      "pop r&b",
      "pop rock",
      "pop synth",
      "pop tween",
      "positive",
      "positive build",
      "post",
      "post rock",
      "power energetic",
      "praise worship",
      "pre school",
      "prestige",
      "prestige luxury",
      "production elements",
      "progressive",
      "progressive house",
      "progressive rock",
      "promos",
      "protestant",
      "psychedelic",
      "pulsing",
      "punk",
      "punk metal",
      "quirky",
      "quirky dramedy",
      "r&b",
      "r&b west coast",
      "ragga",
      "ragga dancehall",
      "ragtime",
      "ramp",
      "ranchera",
      "rap",
      "rap rock",
      "rare groove",
      "rave",
      "reality",
      "reality tv",
      "reggae",
      "reggae dub",
      "religious",
      "remix",
      "retro",
      "reveal",
      "reverse",
      "rhythm bed",
      "riffs musical elements",
      "rise",
      "rock",
      "rock and roll",
      "rock pop",
      "rock psychedelic",
      "rock rocktronica",
      "rock speed metal thrash metal",
      "rock steady",
      "rock surf",
      "rock techno",
      "rockabilly",
      "romance",
      "romantic",
      "romantic comedy",
      "roots",
      "royal",
      "rumba",
      "rural",
      "sadness",
      "salsa",
      "samba",
      "scenery",
      "schlager",
      "sci-fi",
      "science",
      "science technology",
      "science technology drone",
      "score",
      "sea shanty",
      "shamanistic",
      "shoegaze",
      "showbiz fanfare",
      "silent",
      "singer songwriter",
      "sitcom",
      "ska",
      "skate punk",
      "slapstick",
      "slow dance",
      "small drama",
      "small emotions",
      "small ensemble",
      "small group",
      "smooth",
      "smooth hip hop",
      "smooth jazz",
      "sneaky",
      "soap",
      "soap opera",
      "soft",
      "soft house",
      "soft rock",
      "son",
      "song",
      "sophistication",
      "soul",
      "soul r&b",
      "sound design",
      "sound effects",
      "sound elements",
      "sound elements atmospheres",
      "soundscape",
      "soundtrack",
      "south american",
      "southern",
      "southern rock",
      "space drone",
      "spaghetti western",
      "spanish",
      "special occasions funeral",
      "special occasions wedding",
      "speed metal",
      "spiritual",
      "spoof",
      "sport",
      "sport action",
      "sport fanfare",
      "spy",
      "stabs shocks",
      "stadium",
      "stadium rock",
      "sting",
      "story",
      "strange weird",
      "stride boogie",
      "string",
      "string quartet",
      "style",
      "summer holiday",
      "supernatural",
      "surf",
      "suspense",
      "suspense tension",
      "suspense thriller",
      "sweep",
      "swell",
      "swing",
      "swing beat r&b",
      "swoosh",
      "synth",
      "synthwave",
      "talk show",
      "tango",
      "tango nuevo",
      "tasking",
      "tech house",
      "techno",
      "techno trance",
      "technology",
      "tension",
      "tex mex",
      "tex-mex",
      "tex-mex banda norteno",
      "textural",
      "thriller",
      "township",
      "traditional",
      "traditional blues",
      "traditional country",
      "traditional dance",
      "traditional ethnic folk traditional national ethnic",
      "traditional ethnic folk traditional national ethnic fado",
      "traditional world music",
      "tragedy",
      "trailer",
      "trailer promo",
      "trailer score",
      "training",
      "trance",
      "transition element",
      "trap",
      "travel",
      "travel vacation",
      "tribal",
      "trio",
      "trip hop",
      "tropical",
      "tropical house",
      "tv",
      "tween",
      "twist",
      "ufc",
      "uk garage",
      "underscore",
      "underscores",
      "underwater",
      "uplifting",
      "urban",
      "varoous",
      "vaudeville vintage",
      "victorian",
      "vintage",
      "vintage kitsch",
      "vocal",
      "walking bass",
      "waltz",
      "warm drone",
      "weather",
      "wellness relaxation",
      "west coast",
      "west coast hip hop",
      "western",
      "western cowboy",
      "western swing",
      "wind",
      "wooshes swooshes",
      "world",
      "world beat",
      "world games",
      "worship",
      "youthful",
    ],
  "moods":
    [
      "abstract",
      "acceleration",
      "achievement",
      "action",
      "adventurous",
      "affectionate",
      "aftermath",
      "aggressive",
      "agitated",
      "airy",
      "amazement",
      "ambient",
      "angelic",
      "angry",
      "angst",
      "angular",
      "angular disjointed",
      "anthemic",
      "anticipatory",
      "anxious",
      "anxious nervous",
      "apocalyptic",
      "arousing",
      "artful",
      "assertive",
      "atmospheric",
      "atonal",
      "automated",
      "awe inspiring inspiring",
      "ballad",
      "barren",
      "bass",
      "beautiful",
      "bittersweet",
      "blissful",
      "blue",
      "bluesy",
      "boingy",
      "boisterous",
      "bold",
      "bone chill",
      "bouncy",
      "brash",
      "brassy",
      "breaks",
      "breezy",
      "bright",
      "brooding",
      "bubbly",
      "build up",
      "building",
      "bumbling",
      "bump grind",
      "busy",
      "busy frantic",
      "calm",
      "campy",
      "carefree",
      "casino",
      "celebratory",
      "celestial ethereal",
      "cerebral",
      "changing tempo",
      "chaotic",
      "chase",
      "cheeky",
      "cheeky naughty",
      "cheerful",
      "cheerful happy",
      "childlike",
      "chill",
      "cinematic",
      "cold",
      "comedic",
      "comfortable",
      "comforting",
      "comical humorous",
      "conceptual",
      "concerned",
      "confident",
      "confident strong proud",
      "confident strong proud motivational",
      "confrontational",
      "confused",
      "contemplative",
      "contented",
      "cool",
      "country feel",
      "countryside",
      "courageous",
      "creepy",
      "crime",
      "crisis",
      "curious",
      "danceable",
      "dangerous",
      "dangerous threatening",
      "dark",
      "dark exciting",
      "dark ominous",
      "dark sexy",
      "defeated",
      "delicate",
      "delicate gentle",
      "dense",
      "depressing",
      "desire",
      "desperate",
      "destructive",
      "detective",
      "determined",
      "devilish",
      "dignified",
      "disjointed",
      "disturbing",
      "documentary",
      "dominating",
      "doomy",
      "dramatic",
      "dreamy",
      "driven",
      "driving",
      "drums",
      "drunk",
      "drunk stoned",
      "dubstep",
      "dynamic",
      "dystopian",
      "easy going",
      "eccentric",
      "eccentric quirky",
      "ecstatic",
      "edgy",
      "eerie",
      "electro",
      "electronic",
      "elegant",
      "elegant graceful",
      "emotional",
      "emotive",
      "enchanting",
      "energetic",
      "energetic lively",
      "enigmatic",
      "epic",
      "erotic",
      "esoteric",
      "ethereal",
      "euphoric",
      "evil",
      "excited",
      "excitement",
      "exciting",
      "exciting epic",
      "exhilarating",
      "exotic",
      "expectation",
      "explosive",
      "fantasy",
      "fantasy magical",
      "fast",
      "fear",
      "fearful",
      "feel good",
      "female vocal",
      "festive",
      "fiery",
      "flirtatious",
      "floating",
      "flowing",
      "fluid",
      "focused",
      "folksy",
      "foreboding",
      "fragile",
      "frantic",
      "frenzied",
      "frenzied zany",
      "friendly",
      "frightened",
      "frightening",
      "fun",
      "funereal",
      "funky",
      "funny",
      "funny exciting",
      "futuristic",
      "gentle",
      "ghostly",
      "glamorous",
      "gloomy",
      "glory",
      "good time",
      "gothic",
      "graceful",
      "grand majestic",
      "grandiose",
      "grim",
      "grinding",
      "gritty",
      "groove",
      "groovy",
      "groovy dark",
      "groovy exciting",
      "groovy sexy",
      "hallucinatory",
      "happy",
      "happy bright positive",
      "happy positive bright",
      "hard",
      "haunting",
      "heart broken",
      "heartfelt",
      "heartwarming",
      "heavenly",
      "heavy",
      "heavy ponderous",
      "heroic",
      "high energy",
      "high spirited",
      "honest",
      "hopeful",
      "hopeful dark",
      "hopeful exciting",
      "hopeful groovy",
      "hopeful sexy",
      "horror",
      "horrorific",
      "horse riding",
      "humorous",
      "hypnotic",
      "in a classical style",
      "indecisive",
      "industrial",
      "innocent",
      "insistent",
      "inspiration",
      "inspirational",
      "inspirational uplifting",
      "inspiring",
      "inspiring uplifting",
      "intense",
      "intimate",
      "intrigue",
      "intriguing",
      "introspective",
      "jazzy",
      "jittery",
      "joyful",
      "joyous",
      "jubilant",
      "kind",
      "laid back",
      "latin",
      "lazy",
      "leisurely",
      "light",
      "light hearted",
      "lively",
      "lo fi",
      "lonely",
      "longing",
      "lost",
      "lounge",
      "love",
      "love romantic",
      "love romantic sexy",
      "loving",
      "lush",
      "lyrical",
      "macabre",
      "machine like",
      "madcap",
      "magical",
      "majestic",
      "malicious",
      "marching",
      "martial",
      "mean tough",
      "mechanical",
      "mechanical robotic",
      "meditative",
      "melancholic",
      "melancholy",
      "mellow",
      "melodic",
      "melodramatic",
      "menacing",
      "minimal",
      "miraculous",
      "mischievous",
      "moody",
      "motion",
      "motivational",
      "mournful",
      "murderous",
      "mysterious",
      "naïve",
      "naughty",
      "negative to positive",
      "nervous",
      "nervy",
      "neutral",
      "nightmarish",
      "noble",
      "noble dignified",
      "noble majestic prestigious",
      "nostalgic",
      "old school",
      "ominous",
      "optimistic",
      "optimistic positive",
      "outgoing",
      "panic stricken",
      "panoramic",
      "partying",
      "passionate",
      "pastoral",
      "pathos",
      "patriotic",
      "peaceful",
      "percussive",
      "perky",
      "philosophical",
      "plain",
      "playful",
      "playful hopeful",
      "plodding",
      "poignant",
      "ponderous",
      "pop",
      "positive",
      "positive to negative",
      "pounding",
      "powerful",
      "prestigious",
      "pretty",
      "pride",
      "profound",
      "proud",
      "proud motivational",
      "psychedelic",
      "psychological",
      "pulsating",
      "pulsing",
      "punchy",
      "questioning",
      "quiet",
      "quirky",
      "raunchy",
      "raw",
      "rebellious",
      "reflective",
      "relaxed",
      "relaxing",
      "relentless",
      "repetitive",
      "restless",
      "retro",
      "rhythmic",
      "rippling",
      "rising",
      "robotic",
      "rollicking",
      "romantic",
      "rousing",
      "rowdy",
      "running",
      "sacred",
      "sad",
      "sad depressing",
      "sad hopeful",
      "satisfied",
      "saucy",
      "scary",
      "schmaltz",
      "sci fi space",
      "science and technology",
      "seductive",
      "sensing",
      "sensitive",
      "sensual",
      "sentimental",
      "serene",
      "serious",
      "serious determined",
      "sexual",
      "sexy",
      "sexy exciting",
      "sfx",
      "shimmering",
      "shocking",
      "silly",
      "simple",
      "sinister",
      "sleazy",
      "sleepy",
      "slick glossy",
      "slow",
      "slow motion",
      "smooth",
      "sneaking",
      "soaring",
      "soft",
      "solemn",
      "sombre",
      "soothing",
      "sophisticated",
      "sorrow",
      "soul",
      "soulful",
      "sound design",
      "soundscape",
      "spacey",
      "spacious",
      "sparse",
      "spiritual",
      "spooky",
      "sports arena",
      "static",
      "stealthy",
      "strange",
      "strange weird",
      "strength",
      "strong",
      "strong determined",
      "strong powerful",
      "sultry",
      "sunny holiday",
      "supernatural",
      "surreal",
      "suspense",
      "suspense tension",
      "suspenseful",
      "sweet",
      "swinging",
      "swirling",
      "sympathetic",
      "tender",
      "tense",
      "tense groovy",
      "tense hopeful",
      "tension",
      "tentative",
      "terrifying",
      "textures",
      "thoughtful",
      "threatening",
      "time passing",
      "time passing time lapse",
      "tortured",
      "tragic",
      "trailer tools",
      "tranquil",
      "trip hop",
      "trippy",
      "triumphant",
      "troubled",
      "twisted",
      "unsettling",
      "upbeat",
      "uplifting",
      "urgent",
      "victorious",
      "victorious triumphant",
      "violent",
      "walking",
      "warm",
      "water",
      "weird",
      "weird confused",
      "whimsical",
      "wild",
      "wistful",
      "wondrous breathtaking",
      "worried",
      "wry",
      "zany",
      "zen meditation",
    ],
  "instruments":
    [
      "12-string guitar guitar",
      "808",
      "808 bass",
      "a cappella",
      "accordion",
      "accordion concertina",
      "accordion feat",
      "acoustic",
      "acoustic bass",
      "acoustic drum",
      "acoustic drums brushes",
      "acoustic ensemble",
      "acoustic guitar",
      "acoustic nylon string",
      "acoustic piano",
      "african drums",
      "african flute",
      "african percussion",
      "agogo bells",
      "alarms",
      "alpine horn",
      "alto flute",
      "alto saxophone",
      "ambient",
      "ambient sounds",
      "ambient textures",
      "animals",
      "arpeggiator",
      "atmospheres",
      "atmospheric drones",
      "atmospherics",
      "autoharp",
      "background vocals",
      "backing vocals",
      "baglama saz",
      "bagpipes",
      "bajo sexto sexto",
      "balafon",
      "balalaika",
      "band",
      "band ethnic",
      "band jam",
      "band jazz",
      "band pop",
      "band rock",
      "bandoneon",
      "bandoneon concertina feat",
      "banjo",
      "banjo feat",
      "bansuri",
      "baritone saxophone",
      "barrel organ",
      "bass",
      "bass acoustic",
      "bass clarinet",
      "bass clarinet feat",
      "bass distorted fuzz",
      "bass drum",
      "bass electric",
      "bass electronic",
      "bass fretless",
      "bass guitar",
      "bass guitar feat",
      "bass modern",
      "bass slap bass",
      "bass stringed bass double bass",
      "bass synth",
      "bass upright",
      "bass, slap bass",
      "bass, stringed bass double bass",
      "bassoon",
      "bassoon feat",
      "beat",
      "beats",
      "bell",
      "bell tree",
      "bells",
      "bells chimes",
      "bells church",
      "bells sleigh",
      "bells tubular",
      "benders",
      "bendir douf",
      "berimbau",
      "big band",
      "bird song",
      "blues harp",
      "bodhran",
      "bodhran frame drum",
      "body percussion",
      "bongo",
      "bongos",
      "boom",
      "bouzouki",
      "bouzouki greece",
      "bowed fx",
      "braams",
      "brass",
      "brass band",
      "brass ensemble",
      "brass feat",
      "brass section",
      "brazilian guitar",
      "breath fx",
      "brushes",
      "bugle",
      "cabasa",
      "calliope",
      "castanets",
      "celesta",
      "celesta feat",
      "cello",
      "cello feat",
      "celtic harp",
      "chamber orchestra",
      "charango",
      "child vocal",
      "children choir",
      "chimes",
      "chimes tubular bells",
      "choir",
      "choir feat",
      "choir solo",
      "chronometer",
      "church bells",
      "church organ",
      "cimbalom",
      "cimbalom dulcimer",
      "clap",
      "claps",
      "clapsticks",
      "clarinet",
      "clarinet bass",
      "clarinet feat",
      "classical guitar",
      "claves",
      "clavinet",
      "clock",
      "clocks",
      "clockwork",
      "comedy fx",
      "computer video games",
      "concert bass drum",
      "concert flute",
      "concert toms",
      "concertina",
      "conga",
      "congas",
      "contrabass",
      "country band",
      "cowbell",
      "crooner",
      "crotales",
      "crowd fx",
      "cuica",
      "cymbal",
      "cymbals",
      "darbouka",
      "darbuka",
      "darbuka africa",
      "delay",
      "dholak",
      "diatonic accordion",
      "didgeridoo",
      "digeridoo",
      "distorted guitar",
      "distorted synth beds",
      "distortion",
      "dixieland band",
      "dizi",
      "dj samples",
      "dj scratches fx",
      "djembe",
      "djembe africa",
      "dobro",
      "dobro feat",
      "double",
      "double bass",
      "doudouk duduk",
      "drone",
      "drones",
      "drum",
      "drum bass drum feat",
      "drum computer",
      "drum kit",
      "drum line",
      "drum machine",
      "drum machine electronic drums",
      "drum roll",
      "drum rolls",
      "drum set",
      "drum side drum feat",
      "drumming",
      "drums",
      "drums brushed",
      "drums distorted",
      "drums effected",
      "drums electronic",
      "drums electronics",
      "drums feat",
      "drums live",
      "drums looped",
      "drums marching",
      "drums military war",
      "drums programmed",
      "drums sampled",
      "drums solo",
      "duduk",
      "duduk ",
      "dulcimer",
      "dulcitone",
      "dumbek middle east",
      "ebow",
      "echo",
      "effects",
      "effects sound design",
      "electric",
      "electric bass",
      "electric bass guitar",
      "electric drums",
      "electric guitar",
      "electric guitar feat",
      "electric guitar solo",
      "electric guitar, southern africa",
      "electric guitar, western africa central africa",
      "electric guitars",
      "electric organ",
      "electric piano",
      "electric piano feat",
      "electronic",
      "electronic bass",
      "electronic beats",
      "electronic drums",
      "electronic effects",
      "electronic ensemble",
      "electronic fx",
      "electronic instruments",
      "electronic pads",
      "electronic percussion",
      "electronic synth pad",
      "electronics",
      "english horn",
      "erhu",
      "ethnic",
      "ethnic choir",
      "ethnic flutes",
      "ethnic historical non western",
      "ethnic instruments",
      "ethnic percussion",
      "ethnic plucked instruments",
      "ethnic string instruments",
      "ethnic vocal",
      "ethnic wind instruments",
      "explicit lyrics",
      "explosions",
      "fanfares feat",
      "female",
      "female choir",
      "female lead vocals",
      "female oohs aahs",
      "female vocal",
      "female vocals",
      "fender rhodes piano",
      "fender rhodes piano feat",
      "fiddle",
      "filter effects",
      "filter sweep",
      "finger clicks",
      "finger cymbals",
      "finger cymbals finger bells",
      "finger snaps",
      "flamenco guitar",
      "flugelhorn",
      "flugelhorn feat",
      "flute",
      "flute bamboo",
      "flute feat",
      "flute native american",
      "flute ney",
      "flute piccolo",
      "flute solo",
      "flutes",
      "folk group",
      "foot tapping",
      "french",
      "french horn",
      "french horn feat",
      "french horns",
      "fretless bass",
      "full kit",
      "full orchestra",
      "fx",
      "gamelan",
      "gamelan indonesia",
      "gaohu",
      "girls vocal",
      "glass harmonica",
      "glitch",
      "glock",
      "glockenspiel",
      "glockenspiel feat",
      "gong",
      "gongs",
      "gregorian chant",
      "guiro",
      "guitar",
      "guitar 12-string guitar string",
      "guitar acoustic",
      "guitar acoustic feat",
      "guitar acoustic nylon string",
      "guitar acoustic solo",
      "guitar acoustic steel string",
      "guitar acoustic steel strings",
      "guitar baritone",
      "guitar bass",
      "guitar bottleneck slide",
      "guitar bow",
      "guitar cigar box",
      "guitar distorted electric",
      "guitar dobro",
      "guitar echo",
      "guitar effected",
      "guitar electric",
      "guitar filtered",
      "guitar fuzz",
      "guitar harmonics",
      "guitar hawaiian",
      "guitar jazz",
      "guitar nashville high string",
      "guitar pedal steel",
      "guitar slide",
      "guitar spanish",
      "guitar steel",
      "guitar tremolo",
      "guitar wah wah",
      "guitar wah wah feat",
      "guitarron",
      "guitarron bass guitar",
      "guitars",
      "guitars acoustic",
      "guitars electric",
      "guitars electric clean",
      "guzheng",
      "guzheng guzheng zheng",
      "guzheng zither",
      "gypsy violin",
      "hammond",
      "hammond organ",
      "hammond organ feat",
      "hammond organ solo",
      "hand",
      "hand bells",
      "hand clap",
      "hand claps",
      "hand drums",
      "hand percussion",
      "hang drum",
      "harmonica",
      "harmonica feat",
      "harmonium",
      "harp",
      "harp feat",
      "harp solo",
      "harpceltic",
      "harpsichord",
      "hawaiian guitar",
      "heartbeat",
      "hi hat",
      "hits",
      "honky tonk piano",
      "horn",
      "horn french",
      "horns",
      "horns section",
      "human fx",
      "human sounds",
      "humming",
      "hurdy gurdy",
      "individuals drums",
      "instrumental",
      "instruments",
      "irish flute",
      "jazz band",
      "jazz flute",
      "jazz guitar",
      "jazz quartet",
      "jazz trio",
      "jews harp",
      "junk percussion",
      "junk percussion found objects",
      "kalimba",
      "kalimba africa",
      "kalimba sanza",
      "kanun",
      "kanun arabian",
      "kazoo",
      "kettle drums tympani feat",
      "keyboard",
      "keyboard piano",
      "keyboards",
      "keyboards acoustic piano",
      "keyboards electric piano",
      "keyboards synth",
      "keyboards synth pad",
      "keys",
      "kick",
      "kick drum",
      "kit",
      "kora cora",
      "kora harp lute",
      "koto",
      "koto japan",
      "lap steel guitar",
      "lasers",
      "latin",
      "latin band",
      "latin percussion",
      "laughter",
      "legato strings",
      "loop",
      "loops",
      "lute",
      "lyre",
      "machinery",
      "main vocal",
      "male",
      "male choir",
      "male female vocals",
      "male lead vocals",
      "male oohs aahs",
      "male rap",
      "male vocal",
      "male vocals",
      "mallet",
      "mallets",
      "mandolin",
      "mandolin feat",
      "maracas",
      "marching band",
      "marching drum feat",
      "marimba",
      "marimba feat",
      "mbira african thumb piano",
      "mbira thumb piano",
      "mc",
      "mechanical instrument",
      "mellotron",
      "melodic",
      "melodica",
      "metals",
      "military band",
      "military drum",
      "military drums",
      "mixed choir",
      "moog",
      "moog arp",
      "moog feat",
      "mouth harp jews harp",
      "music box",
      "muted trumpet",
      "nay flute arabian",
      "ney",
      "non western brass instruments",
      "non western drums",
      "non western flute",
      "non western harp",
      "non western keyboard",
      "non western mandolin",
      "non western marimba",
      "non western pan pipes",
      "non western penny whistle",
      "non western violin",
      "none",
      "nylon guitar",
      "nylon string guitar",
      "oboe",
      "oboe english horn anglais english horn",
      "oboe feat",
      "ocarina",
      "orchestra",
      "orchestra chamber",
      "orchestra harp",
      "orchestra hit",
      "orchestra hits",
      "orchestra hybrid",
      "orchestra hybrid chamber hit",
      "orchestra large",
      "orchestra percussion",
      "orchestra small",
      "orchestra symphony",
      "organ",
      "organ barrel",
      "organ church",
      "organ church solo",
      "organ electric",
      "organ electric feat",
      "organ hammond",
      "organ harmonium",
      "organ wurlitzer",
      "organs",
      "oud",
      "oud arabian",
      "oud ud",
      "overdrive",
      "pad",
      "pads",
      "pan",
      "pan pipes andes flute",
      "pandeiro",
      "pedal",
      "pedal steel",
      "pedal steel guitar feat",
      "percussion",
      "percussion african",
      "percussion asian",
      "percussion body",
      "percussion ensemble",
      "percussion ethnic",
      "percussion feat",
      "percussion junk found objects",
      "percussion latin",
      "percussion metal",
      "percussion orchestra",
      "percussion shaker",
      "percussion solo",
      "percussion tambourine",
      "percussion tuned",
      "piano",
      "piano accompaniment",
      "piano detuned honky tonk",
      "piano electric",
      "piano feat",
      "piano grand",
      "piano prepared",
      "piano rhodes",
      "piano solo",
      "piano toy",
      "piano upright",
      "pianos",
      "piccolo",
      "pipa",
      "pipa china",
      "pipe organ",
      "pipes",
      "pipes celtic",
      "pipes pan",
      "pitch shift",
      "pitch shift vocal",
      "pizzicato",
      "pizzicato strings",
      "player piano pianola",
      "pop band",
      "processed drums",
      "processed horns",
      "pulse",
      "pulses",
      "qanun",
      "quartet",
      "rain",
      "rainstick",
      "record crackle",
      "recorder",
      "recorder feat",
      "repinique",
      "reverse effects",
      "rhodes",
      "rhodes piano",
      "rhythmic section",
      "rim clicks",
      "rise",
      "riser",
      "risers",
      "robot",
      "rock band",
      "rock orchestra",
      "rythmic",
      "sample",
      "sampled vocal",
      "samples",
      "santoor",
      "sarangi",
      "saxophone",
      "saxophone alto",
      "saxophone alto feat",
      "saxophone bariton",
      "saxophone feat",
      "saxophone section",
      "saxophone soprano",
      "saxophone soprano feat",
      "saxophone tenor",
      "saz",
      "saz arabic",
      "saz lute baglama",
      "scat",
      "scratching",
      "screech",
      "sequencer",
      "sfx",
      "sfx sound effects",
      "sfx sound effects alarm",
      "sfx sound effects animal",
      "sfx sound effects automation machinery",
      "sfx sound effects background",
      "sfx sound effects breathing",
      "sfx sound effects clockwork grandfather clock",
      "sfx sound effects comedic fx",
      "sfx sound effects cops police",
      "sfx sound effects countdown",
      "sfx sound effects crowd",
      "sfx sound effects electronic sounds",
      "sfx sound effects explosions",
      "sfx sound effects fantasy sci fi sounds",
      "sfx sound effects filters",
      "sfx sound effects finger clicks",
      "sfx sound effects foot stomps",
      "sfx sound effects guns",
      "sfx sound effects hand claps",
      "sfx sound effects heartbeat",
      "sfx sound effects hiss crackle",
      "sfx sound effects horns",
      "sfx sound effects horror",
      "sfx sound effects human",
      "sfx sound effects human whistle",
      "sfx sound effects lasers zaps",
      "sfx sound effects record crackle",
      "sfx sound effects record scratch",
      "sfx sound effects selectronic sounds",
      "sfx sound effects siren",
      "sfx sound effects sonar",
      "sfx sound effects space",
      "sfx sound effects static crackle",
      "sfx sound effects sweeps whooshe",
      "sfx sound effects wind",
      "shaker",
      "shakers",
      "shakuhachi",
      "shakuhachi japan",
      "shamisen",
      "shamisen japan",
      "shout",
      "shouts",
      "sidechain",
      "singing bowls",
      "siren",
      "sitar",
      "sleigh bells",
      "sleigh bells feat",
      "slide",
      "slide guitar",
      "slide guitar feat",
      "small electronic percussion",
      "small orchestra",
      "snaps",
      "snare",
      "snare drum",
      "solo instrument",
      "song",
      "soprano",
      "soprano saxophone",
      "sound",
      "sound deisgn",
      "sound effects",
      "sound fx",
      "space fx",
      "spanish guitar",
      "spoons",
      "standard piano",
      "static white noise",
      "steel",
      "steel drum",
      "steel drums",
      "steel guitar",
      "steel pan",
      "stereo fx",
      "sticks",
      "stomps",
      "string",
      "string bass 1",
      "string ensemble",
      "string orchestra",
      "string quartet",
      "string section",
      "stringed",
      "strings",
      "strings feat",
      "strings orchestra",
      "strings pizzicato",
      "strings pizzicato feat",
      "strings plucked",
      "strings samples",
      "strings solo",
      "strings staccato",
      "sub bass",
      "surdo",
      "surf band",
      "surf guitar",
      "suspended cymbal",
      "sweeps",
      "synth",
      "synth bass",
      "synth brass",
      "synth choir",
      "synth drums",
      "synth feat",
      "synth lead",
      "synth leads",
      "synth pad",
      "synth pads",
      "synth poly",
      "synth pulses",
      "synth strings",
      "synth sweep",
      "synthesizer",
      "synthesizer bells",
      "synthesizer moog arp",
      "synthesizer vocals",
      "synthesizers",
      "synths",
      "tabla",
      "tabla india",
      "taiko",
      "taiko drum",
      "taiko drums",
      "tamborim",
      "tamborin",
      "tambourine",
      "tambura",
      "tape noise",
      "tar",
      "tenor",
      "tenor saxophone",
      "textures",
      "theremin",
      "tick tocks",
      "timbale",
      "timbales",
      "timbau",
      "timpani",
      "tin whistle",
      "tom",
      "toms",
      "toy instruments",
      "toy piano",
      "tremolo",
      "triangle",
      "trombone",
      "trombone feat",
      "trumpet",
      "trumpet cornet",
      "trumpet feat",
      "trumpet muted",
      "trumpets",
      "tuba",
      "tuba feat",
      "tuba sousaphone",
      "tubular bells",
      "tubular bells church bells chimes",
      "tuned percussion",
      "turntables",
      "tv show band",
      "tympani",
      "udu",
      "uillean pipes ireland",
      "ukelele",
      "ukulele",
      "ukulele feat",
      "upright",
      "upright bass",
      "upright bass feat",
      "vibes",
      "vibraphone",
      "vibraphone feat",
      "vielle",
      "vinyl fx",
      "viola",
      "violin",
      "violin fiddle feat",
      "violin fiddle solo",
      "violins",
      "vocal",
      "vocal accents",
      "vocal fx",
      "vocal sample",
      "vocal samples",
      "vocal textures feat",
      "vocal voices feat",
      "vocal voices solo",
      "vocals",
      "vocals male",
      "vocals solo female",
      "vocals solo male",
      "vocoder",
      "voice",
      "voice fx",
      "voice sounds",
      "voices",
      "voices fx",
      "vox",
      "wah",
      "wah wah guitar",
      "wash board",
      "water fx",
      "waterphone",
      "western brass instruments",
      "western drums",
      "western flute",
      "western harp",
      "western keyboard",
      "western mandolin",
      "western marimba",
      "western pan pipes",
      "western penny whistle",
      "western percussion",
      "western violin",
      "whisper",
      "whistle",
      "whistletin",
      "whistling",
      "whistling feat",
      "whoosh",
      "wind",
      "wind chimes",
      "wind chimes bell tree",
      "wind flute",
      "wind other",
      "wind reed",
      "winds",
      "wobble bass feat",
      "wood block",
      "woodwind",
      "woodwind section",
      "woodwinds",
      "woodwinds ensemble",
      "woodwinds feat",
      "woodwinds section",
      "wordless",
      "wurlitzer",
      "wurlitzer organ",
      "xiao",
      "xylophone",
      "xylophone feat",
      "xylophone glockenspiel",
      "yangqin china",
      "yangqin yangxin",
      "zaps",
      "zither",
    ],
}
